### ISSUE TITLE
Array parameter eaten outside of if/while block

### ISSUE THREAD

**Issue by mastef** [HaxeFoundation/as3hx#316]
as3 code for example:
```actionscript
package {
    public class Issue316 {
        public function Issue316(param1:int = 1) {
            var _loc1_:int = 1;
            this["hint" + _loc1_]; // <--
            this["hint" + param1]; // <--
            this["hint" + anything]; // <--
            if(1==1) {
               this["hint" + _loc1_];
               this["hint" + param1];
               this["hint" + anything];
            }
            while(_loc1_ != 1)
            {
               this["hint" + _loc1_];
               this["hint" + param1];
               this["hint" + anything];
            }
        }
    }
}
```
expected result
```haxe

class Issue316
{
    public function new(param1 : Int = 1)
    {
        var _loc1_ : Int = 1;
        this["hint" + _loc1_];  // <--  
        this["hint" + param1];  // <--  
        this["hint" + anything];  // <--  
        if (1 == 1)
        {
            this["hint" + _loc1_];
            this["hint" + param1];
            this["hint" + anything];
        }
        while (_loc1_ != 1)
        {
            this["hint" + _loc1_];
            this["hint" + param1];
            this["hint" + anything];
        }
    }
}
```
actual result
```haxe
class Issue316
{
    public function new(param1 : Int = 1)
    {
        var _loc1_ : Int = 1;
        this["hint"];  // <--  
        this["hint"];  // <--  
        this["hint"];  // <--  
        if (1 == 1)
        {
            this["hint" + _loc1_];
            this["hint" + param1];
            this["hint" + anything];
        }
        while (_loc1_ != 1)
        {
            this["hint" + _loc1_];
            this["hint" + param1];
            this["hint" + anything];
        }
    }
}
```

**Comment by mastef** [comment]
Doesn't happen in haxelib version ( 1.0.6 ) so should be one of the latest updates

**Comment by SlavaRa** [comment]
Wow, this is a bug, but ActionScript code does not make any sense :(

**Comment by mastef** [comment]
Ya, i stripped it down from `this["hint"].gotoAndPlay("abc");` for clarity ( same results when a method call follows the array declaration )

`this["hint" + anything].gotoAndPlay("abc");` turns into `this["hint"].gotoAndPlay("abc");`

**Comment by SlavaRa** [comment]
```this["hint" + anything].gotoAndPlay("abc");``` != ```this["hint" + anything];```

**Comment by mastef** [comment]
Correct.. as I said, same results for both cases 😄 

as3 code for example:
```actionscript
package {
    public class Issue {
        public function Issue(param1:int = 1) {
            var _loc1_:int = 1;
            var a, b, c;
            this["hint" + _loc1_]; // <--
            this["hint" + param1]; // <--
            this["hint" + anything]; // <--
            this["hint" + _loc1_].gotoAndPlay("on"); // <--
            this["hint" + param1].gotoAndPlay("on"); // <--
            this["hint" + anything].gotoAndPlay("on"); // <--
            a = this["hint" + _loc1_];
            b = this["hint" + param1];
            c = this["hint" + anything];
            if(1==1) {
               this["hint" + _loc1_];
               this["hint" + param1];
               this["hint" + anything];
               this["hint" + _loc1_].gotoAndPlay("on");
               this["hint" + param1].gotoAndPlay("on");
               this["hint" + anything].gotoAndPlay("on");
               a = this["hint" + _loc1_];
               b = this["hint" + param1];
               c = this["hint" + anything];
            }
            while(_loc1_ != 1)
            {
              this["hint" + _loc1_];
              this["hint" + param1];
              this["hint" + anything];
              this["hint" + _loc1_].gotoAndPlay("on");
              this["hint" + param1].gotoAndPlay("on");
              this["hint" + anything].gotoAndPlay("on");
              a = this["hint" + _loc1_];
              b = this["hint" + param1];
              c = this["hint" + anything];
            }
        }
    }
}
```
expected result
```haxe
class Issue
{
    public function new(param1 : Int = 1)
    {
        var _loc1_ : Int = 1;
        var a;
        var b;
        var c;
        this["hint" + _loc1_];  // <--  
        this["hint" + param1]];  // <--  
        this["hint" + anything];  // <--  
        this["hint" + _loc1_].gotoAndPlay("on");  // <--  
        this["hint" + param1]].gotoAndPlay("on");  // <--  
        this["hint" + anything].gotoAndPlay("on");  // <--  
        a = this["hint" + _loc1_];
        b = this["hint" + param1];
        c = this["hint" + anything];
        if (1 == 1)
        {
            this["hint" + _loc1_];
            this["hint" + param1];
            this["hint" + anything];
            this["hint" + _loc1_].gotoAndPlay("on");
            this["hint" + param1].gotoAndPlay("on");
            this["hint" + anything].gotoAndPlay("on");
            a = this["hint" + _loc1_];
            b = this["hint" + param1];
            c = this["hint" + anything];
        }
        while (_loc1_ != 1)
        {
            this["hint" + _loc1_];
            this["hint" + param1];
            this["hint" + anything];
            this["hint" + _loc1_].gotoAndPlay("on");
            this["hint" + param1].gotoAndPlay("on");
            this["hint" + anything].gotoAndPlay("on");
            a = this["hint" + _loc1_];
            b = this["hint" + param1];
            c = this["hint" + anything];
        }
    }
}
```
actual result
```haxe

class Issue
{
    public function new(param1 : Int = 1)
    {
        var _loc1_ : Int = 1;
        var a;
        var b;
        var c;
        this["hint"];  // <--  
        this["hint"];  // <--  
        this["hint"];  // <--  
        this["hint"].gotoAndPlay("on");  // <--  
        this["hint"].gotoAndPlay("on");  // <--  
        this["hint"].gotoAndPlay("on");  // <--  
        a = this["hint" + _loc1_];
        b = this["hint" + param1];
        c = this["hint" + anything];
        if (1 == 1)
        {
            this["hint" + _loc1_];
            this["hint" + param1];
            this["hint" + anything];
            this["hint" + _loc1_].gotoAndPlay("on");
            this["hint" + param1].gotoAndPlay("on");
            this["hint" + anything].gotoAndPlay("on");
            a = this["hint" + _loc1_];
            b = this["hint" + param1];
            c = this["hint" + anything];
        }
        while (_loc1_ != 1)
        {
            this["hint" + _loc1_];
            this["hint" + param1];
            this["hint" + anything];
            this["hint" + _loc1_].gotoAndPlay("on");
            this["hint" + param1].gotoAndPlay("on");
            this["hint" + anything].gotoAndPlay("on");
            a = this["hint" + _loc1_];
            b = this["hint" + param1];
            c = this["hint" + anything];
        }
    }
}

```

**Comment by mastef** [comment]
I think this is related : 
`gotoAndStop(param1 + 2);`
ends up as : 
`gotoAndStop(param1);`

**Comment by SlavaRa** [comment]
I'll fix it tonight.

**Comment by mastef** [comment]
Watch out when testing, this seems to only happen to the first file in a directory that is being processed. The following files don't have this issue

**Comment by mastef** [comment]
https://github.com/HaxeFoundation/as3hx/commit/2b8bdc88be67478a1dd4154678419a5a53e664bb?w=1#diff-8f512c0986dbff22af802aba4b7463e3R2209

This change broke it, changing this line to `                case _: rvalue = e2;` "fixes" it for me, but I don't know what else it would break. My "fix" doesn't seem like the previous code.

**Comment by mastef** [comment]
Yeah, I think that's a side-effect. `process()` seems to be missing var initializations to clean up the last file. I guess changing  :

```haxe
    public function process(program : Program, writer : Output):Map<String, Bool> {
        warnings = new Map();

        //list of imported types must be reseted for each file,
        //as only one instance of Writer write all the files
        imported = [];
```  
to
```haxe
    public function process(program : Program, writer : Output):Map<String, Bool> {
        warnings = new Map();

        //list of imported types must be reseted for each file,
        //as only one instance of Writer write all the files
        imported = [];

        //we're in a new file, so reset all vars
        lvl = 0;
        varCount = 0;
        context = new Map();
        contextStack = new Array();
        inArrayAccess = false;
        inEField = false;
        inE4XFilter = false;
        inLvalAssign = false;
        lineIsDirty = false;
        rvalue = null;

        typeImportMap = new Map<String,String>();
        genTypes = [];
```
would make sense?

**Comment by mastef** [comment]
So the test case was tainted by that missing clean up. If we clean up `rvalue` by adding this to `writeEBinop` : 
```
    function writeEBinop(op:String, e1:Expr, e2:Expr, newLineAfterOp:Bool):BlockEnd {
        rvalue = null;
```
Then it will happen for every line :

```as
package {
    public class Hint {
        public function Hint(param1:int = 1) {

           gotoAndStop(param1 + 1);
           gotoAndStop(param1 + "hello");
           gotoAndStop("a" + "hello"); 
           if(_loc2_ < this.regionNum)
           {
               _loc3_ = new ColorTransform(a / 255);
               _loc3_ = new ColorTransform(a * 255);
               _loc3_ = new ColorTransform(a + 255);
               _loc3_ = new ColorTransform(a - 255);
           }
            this["hint" + _loc1_];
            this["hint" + param1];
            this["hint" + anything];
            this["hint" + _loc1_].gotoAndPlay("on" + 0);
            this["hint" + param1].gotoAndPlay("on" + 1);
            this["hint" + anything].gotoAndPlay("on" + 2);
            a = this["hint" + _loc1_];
            b = this["hint" + param1];
            c = this["hint" + anything];

            while (_loc2_ < this.regionNum) {
                // something
            }
            
            if(1==1) {
               gotoAndStop(param1 + 2); 
               this["hint" + _loc1_];
               this["hint" + param1];
               this["hint" + anything];
               this["hint" + _loc1_].gotoAndPlay("on");
               this["hint" + param1].gotoAndPlay("on");
               this["hint" + anything].gotoAndPlay("on");
               a = this["hint" + _loc1_];
               b = this["hint" + param1];
               c = this["hint" + anything];
            }
            while(_loc1_ != 1)
            {
              gotoAndStop(param1 + 2); 
              this["hint" + _loc1_];
              this["hint" + param1];
              this["hint" + anything];
              this["hint" + _loc1_].gotoAndPlay("on");
              this["hint" + param1].gotoAndPlay("on");
              this["hint" + anything].gotoAndPlay("on");
              a = this["hint" + _loc1_];
              b = this["hint" + param1];
              c = this["hint" + anything];
            }
        }
    }
}
```

result : 

```hx

class Hint
{
    public function new(param1 : Int = 1)
    {
        gotoAndStop(param1);
        gotoAndStop(param1);
        gotoAndStop("a");
        if (_loc2_)
        {
            _loc3_ = new ColorTransform(a);
            _loc3_ = new ColorTransform(a);
            _loc3_ = new ColorTransform(a);
            _loc3_ = new ColorTransform(a);
        }
        this["hint"];
        this["hint"];
        this["hint"];
        this["hint"].gotoAndPlay("on");
        this["hint"].gotoAndPlay("on");
        this["hint"].gotoAndPlay("on");
        a = this["hint"];
        b = this["hint"];
        c = this["hint"];
        
        while (_loc2_)
        {  // something  
            
        }
        
        if (1 == 1)
        {
            gotoAndStop(param1);
            this["hint"];
            this["hint"];
            this["hint"];
            this["hint"].gotoAndPlay("on");
            this["hint"].gotoAndPlay("on");
            this["hint"].gotoAndPlay("on");
            a = this["hint"];
            b = this["hint"];
            c = this["hint"];
        }
        while (_loc1_ != 1)
        {
            gotoAndStop(param1);
            this["hint"];
            this["hint"];
            this["hint"];
            this["hint"].gotoAndPlay("on");
            this["hint"].gotoAndPlay("on");
            this["hint"].gotoAndPlay("on");
            a = this["hint"];
            b = this["hint"];
            c = this["hint"];
        }
    }
}
```

The issue is this : `rvalue != null` check : https://github.com/HaxeFoundation/as3hx/blob/master/src/as3hx/Writer.hx#L2229

If we remove this check, the output is written correctly. OR if we give `rvalue` *any* kind of value - e.g. `e1` or `e2`... ( the output is the same ). Any idea what `rvalue` is used for and when it should be really cleaned up?

**Comment by SlavaRa** [comment]
@mastef I checked the last wizard and I do not have generation errors

**Comment by mastef** [comment]
@SlavaRa  was it the first file in the directory? as mentioned above this only affects the first file, because vars are not cleared up properly. apply this patch and run again https://github.com/HaxeFoundation/as3hx/issues/316#issuecomment-346021257

**Comment by mastef** [comment]
@SlavaRa in options change from 1.0.6 to GIT and hit compile : http://as3hx.spacemages.com/#46713

**Comment by mastef** [comment]
@SlavaRa did you have time to take a look? As this is a huge issue with the current git version

**Comment by SlavaRa** [comment]
tonight

**Comment by mastef** [comment]
Any ideas?

**Comment by SlavaRa** [comment]
I fixed, I'll push fix after work, now busy

**Comment by mastef** [comment]
Ok, time to test it! 😄

**Comment by SlavaRa** [comment]
@mastef please try last master

**Comment by mastef** [comment]
@SlavaRa Thanks! [Looks like it's fixed](http://as3hx.spacemages.com/#080fA) 😄 

Still what do you think about the [clean up in `process`](https://github.com/HaxeFoundation/as3hx/issues/316#issuecomment-346021257)?
 Right now when you process multiple files, the global static vars are not cleaned up when a new file is being processed. So old settings are still present, although we're in a new file.

**Comment by SlavaRa** [comment]
i will check it today
